import Head from "next/head";
import Nav from "./components/Nav";
import Hero from "./components/Hero";
export default function Home() {
	return (
		<>
			<Head>
				<title>GOAT🐐</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Nav />
			<Hero />
		</>
	);
}
